name: Pterodactyl Egg Upload - Docker Image

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username blockplacer4 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghrc.io/blockplacer4/solus-egg:latest
          docker push ghrc.io/blockplacer4/solus-egg:latest